import type { SlotKind } from '../types'

/**
 * Words the dice can roll for each kind of blank. They lean silly on purpose —
 * a tale filled entirely at random should still be worth reading aloud.
 */
const BANKS: Record<SlotKind, string[]> = {
  name: [
    'Bramblewick',
    'Seraphina',
    'Podge',
    'Ellowyn',
    'Mortimer',
    'Nim',
    'Thistlebottom',
    'Auberon',
    'Wren',
    'Grumbleshanks',
    'Isolde',
    'Fig',
  ],
  noun: [
    'teapot',
    'kneecap',
    'wheelbarrow',
    'bagpipe',
    'doorknob',
    'pickle jar',
    'trombone',
    'mousetrap',
    'wig',
    'lampshade',
    'harpoon',
    'waffle iron',
  ],
  'plural-noun': [
    'goblins',
    'accordions',
    'turnips',
    'bathtubs',
    'librarians',
    'anvils',
    'mittens',
    'barnacles',
    'trapdoors',
    'gargoyles',
    'dumplings',
    'kazoos',
  ],
  adjective: [
    'soggy',
    'majestic',
    'suspicious',
    'lopsided',
    'radiant',
    'clammy',
    'thunderous',
    'velvety',
    'ill-tempered',
    'shimmering',
    'crumbly',
    'ferocious',
  ],
  verb: [
    'waddle',
    'yodel',
    'somersault',
    'negotiate',
    'gallop',
    'sneeze',
    'juggle',
    'tiptoe',
    'bellow',
    'levitate',
    'shuffle',
    'wrestle',
  ],
  'verb-ing': [
    'wobbling',
    'moonwalking',
    'shrieking',
    'knitting',
    'cartwheeling',
    'grumbling',
    'sparkling',
    'hiccuping',
    'stampeding',
    'whispering',
    'flossing',
    'galloping',
  ],
  'verb-past': [
    'exploded',
    'fainted',
    'boogied',
    'vanished',
    'belched',
    'pirouetted',
    'melted',
    'apologised',
    'cannonballed',
    'sulked',
    'blossomed',
    'skidded',
  ],
  adverb: [
    'dramatically',
    'sleepily',
    'ferociously',
    'politely',
    'sideways',
    'urgently',
    'gracefully',
    'suspiciously',
    'loudly',
    'tenderly',
    'clumsily',
    'triumphantly',
  ],
  animal: [
    'badger',
    'sea otter',
    'alpaca',
    'pigeon',
    'axolotl',
    'moose',
    'hedgehog',
    'narwhal',
    'goose',
    'sloth',
    'ferret',
    'peacock',
  ],
  place: [
    'Cloudmere',
    'Gravy Hollow',
    'the Whispering Fen',
    'Thornhaven',
    'Puddleton',
    'the Glass Steppes',
    'Ashenvale',
    'Mount Wobble',
    'the Hushed Isles',
    'Nettlebrook',
    'Sunkenmoor',
    'Bellhollow',
  ],
  food: [
    'dumplings',
    'blackberry jam',
    'pickled eggs',
    'honeycake',
    'cold porridge',
    'buttered toast',
    'plum pudding',
    'garlic soup',
    'marzipan',
    'fish pie',
    'candied ginger',
    'cheese wheels',
  ],
  number: ['three', 'seven', 'twelve', 'forty', 'a hundred', 'nine', 'two', 'six hundred'],
  color: [
    'moss green',
    'plum',
    'silver',
    'burnt orange',
    'midnight blue',
    'buttercup yellow',
    'rose gold',
    'inky black',
    'seafoam',
    'crimson',
    'lilac',
    'copper',
  ],
  occupation: [
    'cheesemonger',
    'lighthouse keeper',
    'plumber',
    'bard',
    'beekeeper',
    'tax collector',
    'clockmaker',
    'sailor',
    'baker',
    'librarian',
    'blacksmith',
    'juggler',
  ],
  'body-part': [
    'elbow',
    'left ear',
    'nostril',
    'kneecap',
    'thumb',
    'eyebrow',
    'shin',
    'pinky toe',
    'chin',
    'shoulder blade',
  ],
  exclamation: [
    'Great gravy!',
    'Oh crumbs!',
    'By the moons!',
    'Yikes!',
    'Well, blast it!',
    'Sweet biscuits!',
    'Egads!',
    'Not again!',
    'Hoo boy!',
    'Mercy me!',
  ],
  sound: [
    'ka-thunk',
    'squelch',
    'ping',
    'whumpf',
    'tinkle',
    'gloop',
    'ker-splat',
    'hiss',
    'boing',
    'rumble',
  ],
  'magic-word': [
    'Fizzlewump',
    'Abraca-dabbra',
    'Snorgleplix',
    'Vermilliox',
    'Wobbledeeg',
    'Zanzibopp',
    'Thrimble',
    'Kalamazoo',
    'Pfefferknoot',
    'Squibbly',
  ],
}

/** A random suggestion for a blank, never repeating the word already there. */
export function suggestWord(kind: SlotKind, avoid?: string): string {
  const bank = BANKS[kind]
  const options = bank.filter((word) => word.toLowerCase() !== avoid?.trim().toLowerCase())
  const pool = options.length > 0 ? options : bank
  return pool[Math.floor(Math.random() * pool.length)]
}

/** The first few bank entries, shown as tappable chips under a prompt. */
export function exampleWords(kind: SlotKind, count = 3): string[] {
  const bank = [...BANKS[kind]]
  const picks: string[] = []
  while (picks.length < count && bank.length > 0) {
    picks.push(...bank.splice(Math.floor(Math.random() * bank.length), 1))
  }
  return picks
}
